# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and index.js
COPY package*.json ./
COPY index.js ./

# Install dependencies, ignoring scripts if any
RUN npm install --ignore-scripts

# Expose port if needed (MCP uses stdio so no port exposed)

# Start the server
CMD ["node", "index.js"]
